# Generated by Django 3.2.7 on 2024-10-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, related_name='_authentication_userprofile_friend_requests_+', to='authentication.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_authentication_userprofile_friends_+', to='authentication.UserProfile'),
        ),
    ]
