# Generated by Django 3.2.7 on 2024-10-22 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_invitation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
