version: '3.9'

services:
  nginx:
    depends_on:
      - backend
    build: ./frontend
    container_name: nginx
    volumes:
      - ./frontend/front:/var/www/html
    restart: on-failure
    ports:
      - "81:81"
    networks:
      - frontend

  backend:
    build: ./backend
    container_name: backend
    # environment:
    #   - DJANGO_SETTINGS_MODULE=setup.settings
    volumes:
      - ./backend/project:/project
    restart: on-failure
    networks:
      - frontend
networks:
  frontend:
    driver: bridge
