# Generated by Django 3.2.7 on 2024-10-06 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
