# Generated by Django 3.2.7 on 2024-10-14 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0004_game_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='room_name',
        ),
    ]
