# Generated by Django 3.2.7 on 2024-10-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
